name: Build ubuntu-toolbox
on:
  push:
    branches:
      - 'main'
    paths:
      - 'ubuntu/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Login to Redhat Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_REGISTRY_USERNAME }}
          password: ${{ secrets.REDHAT_REGISTRY_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push ubuntu-toolbox
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ubuntu/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ubuntu-toolbox:latest
